apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagbot
spec:
  selector:
    matchLabels:
      app: dagbot
  replicas: 1
  template:
    metadata:
      labels:
        app: dagbot
    spec:
      containers:
      - name: dagbot
        image: daggy1234/dagbot:latest
        envFrom:
          - configMapRef:
              name: config
        resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 50m
              memory: 200Mi
