token: "discord bot token"
gapikey: "Google Cloud API key"
sentryurl: "Sentry Error URL"
dagpitoken: "https://dagpi.xyz"
onreadyurl: "webhook url"
dbhost: ""
database: ""
user: ""
dbpassword: ""
cbkey: "travitia.xyz key"
deepapikey: "deepai api key"
errorwebhook: "webhook"
guildlog: "webhook url"
giphykey: "Gphy API"
hpapikey: "HP API"
imgflipuser: "username"
imgflippass: "password"
ksofttoken: "Token {ksoft.si}"
nasaapikey: "Nasa Api key"
weatherapi: "OpenWeather API"
rapidapi: "Rapid API"
dankapi: "Private ignore"